/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
    '/vueuse/': RouteRecordInfo<'/vueuse/', '/vueuse', Record<never, never>, Record<never, never>>,
    'web3': RouteRecordInfo<'web3', '/web3', Record<never, never>, Record<never, never>>,
    '/web3/accounts': RouteRecordInfo<'/web3/accounts', '/web3/accounts', Record<never, never>, Record<never, never>>,
    '/web3/create-account': RouteRecordInfo<'/web3/create-account', '/web3/create-account', Record<never, never>, Record<never, never>>,
    '/web3/signedTransaction': RouteRecordInfo<'/web3/signedTransaction', '/web3/signedTransaction', Record<never, never>, Record<never, never>>,
    '/web3/transaction': RouteRecordInfo<'/web3/transaction', '/web3/transaction', Record<never, never>, Record<never, never>>,
    'web3-meta-mask': RouteRecordInfo<'web3-meta-mask', '/web3-meta-mask', Record<never, never>, Record<never, never>>,
    '/web3-meta-mask/accounts': RouteRecordInfo<'/web3-meta-mask/accounts', '/web3-meta-mask/accounts', Record<never, never>, Record<never, never>>,
    '/web3-meta-mask/create-account': RouteRecordInfo<'/web3-meta-mask/create-account', '/web3-meta-mask/create-account', Record<never, never>, Record<never, never>>,
    '/web3-meta-mask/signedTransaction': RouteRecordInfo<'/web3-meta-mask/signedTransaction', '/web3-meta-mask/signedTransaction', Record<never, never>, Record<never, never>>,
    '/web3-meta-mask/transaction': RouteRecordInfo<'/web3-meta-mask/transaction', '/web3-meta-mask/transaction', Record<never, never>, Record<never, never>>,
    'web3-to-contract': RouteRecordInfo<'web3-to-contract', '/web3-to-contract', Record<never, never>, Record<never, never>>,
  }
}
